apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-auth-svc
spec:
  selector:
    matchLabels:
      app: mysql-auth-svc
  serviceName: mysql-auth-svc-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-auth-svc
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-auth-svc
        # command: [ '/bin/sh' ]
        # args: ['-c', 'tail -f /dev/null']
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: auth-svc
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: auth-svc
        - name: NODE_ENV
          value: development
        ports:
        - containerPort: 3306
          name: mysql
      #   volumeMounts:
      #   - name: mysql-auth-svc-persistent-storage
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-auth-svc-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-auth-svc-pv-claim